### ISSUE TITLE
Trying to access Azure Blob Storage: "Invalid audience claim in token" when requesting with scope that is different from application ID  

### ISSUE THREAD

**Issue by nickymezzina** [antarctica/flask-entra-auth#11]
In my use case we run a Flask/Dash web app that users will log in with oauth, retrieve an access_token that will then make up a token credential for BlobServiceClient([storage url], credential=token_credential). 

For the access token to work towards Azure Storage, and according to Microsoft the resource ID to use is https://storage.azure.com (see https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app?tabs=dotnet#azure-storage-resource-id).

But I bump into a problem with the audience validation implemented in flask-azure-oauth/tokens.py and authlib/jose/rfc7519/claims.py. I believe that if after the authorization I try to acquire a token with the scopes "https://storage.azure.com/user_impersonation" the resource ID "https://storage.azure.com" is compared to both the application ID and "api://[application ID]" and throws an error if they're not the same:
`{"errors": [{"id": "8766be6e-ac8d-430f-8226-c67dcea2fc9c", "status": 401, "title": "Invalid audience claim in token", "detail": "The JSON Web Token (JWT) used as a token does not have the correct audience. Ensure you are using the correct token and try again, or contact support."}]}`

I know they're not the same and they shouldn't be as BlobServiceClient will connect to Azure Storage which can be considered an external service to the Flask application. I don't get the validation error when I expose an API and use it as "api://[application ID]/user_impersonation" as scope in the access token request (and thus it 'api://[application ID]' becomes the audience), but if I do that then Azure Storage gives me its own version of the same error:
`RequestId:265cf5a0-101e-0035-47f6-c24fb2000000
Time:2020-11-25T06:46:38.2775341Z
ErrorCode:AuthenticationFailed
Error:None
AuthenticationErrorDetail:Audience validation failed. Audience did not match.`

Is the package's token validation too restrictive as to which resources can be used within the web app? Is there an example of an use case where a Flask app can log on users and then within the app an access token can be requested for Azure Storage access?

Thanks in advance!

**Comment by nickymezzina** [comment]
As a troubleshoot I tested to add 'https://storage.azure.com' line at line 106 in the tokens.py file and it helped, the audience validation didn't throw an error and the application could use the access_token that Azure accepted for blob reading.

`"aud": {
                "essential": True,
                "values": [
                    'https://storage.azure.com',
                    service_app_id,  # used by version 2.0 tokens
                    f"api://{ service_app_id }",  # used by version 1.0 tokens
                ],
            },`

**Comment by felnne** [comment]
Hi @nickymezzina,

Thanks for highlighting this. 

> Is there a reason to limit access token audiences to a client?

I would say this is likely an oversight on my part, in that I don't use the blob storage feature and so haven't hit this problem. I also deliberately kept things as restrictive as possible.

I'm happy to make amendments as necessary for this to work however. I think the best thing would be to add a new optional config option to pass a list of audience values for situations like this, as I imagine there'll be other services that will require similar additions.

I won't be able to add this for until at least the week after next due to other work commitments.

**Comment by nickymezzina** [comment]
@felnne Thanks for looking into it, and configurable validation options sounds good.

**Comment by nickymezzina** [comment]
@felnne is it OK if I fork the repo to implement a quick workaround to use in my project?

**Comment by felnne** [comment]
Hi,

Of course, I’m also happy to review any pull-requests but if you’ve already solved this for your use-case it may be easier to wait for me to do it.

Thanks,
Felix.

**Comment by nickymezzina** [comment]
> Hi, Of course, I’m also happy to review any pull-requests but if you’ve already solved this for your use-case it may be easier to wait for me to do it. Thanks, Felix. 
I don't think I will make any pull request. The fork and [branch](https://github.com/nickymezzina/flask-azure-oauth/compare/feature-azure-storage-is-valid-audience) I added isn't a solution per se. Only a quick inelegant workaround to use in the meantime so I can work ahead on other parts of my app. Once you had time to implement a more elegant solution and release it I can switch back to the main package and use the new features.

**Comment by felnne** [comment]
@nickymezzina for info I have rewritten this package based on a newer version of AuthLib.

I haven't added the configurable audience to the new version but the code is much easier to work with now so doing that would be less effort.

If this is still something that would be useful please re-open this issue and I'm happy to take a look (through a contribution would be ideal).
