### ISSUE TITLE
Is there anyway to ignore/bypass Issuer validation?

### ISSUE THREAD

**Issue by bpasham** [antarctica/flask-entra-auth#14]
The situation is with MultiTenant and B2C applications, there is no fixed "Tenant Id" as the authority we request is by /organizations or /consumers or /common
Tenant Id has to be validated against a database which can happen only from within the protected resource or a separate wrapper after the token validation - wondering if you can provide any suggestions on achieving this. like passing in any options argument to choose any validations to ignore.

Appreciate your help.

**Comment by felnne** [comment]
Hi @bpasham, that's an interesting question and I don't have an immediate answer.

For context this package was/is designed to meet an internal need, which currently precludes multi-tenant and B2C apps.

That said, I'm happy to help incorporate other features that will meet the needs of others, though my time to contribute those directly is extremely limited.

My initial though is that perhaps the validation method for each claim should be pluggable, in that you could define a custom method to say check the issuer against a database and configure this package to use that by passing a reference to that method.

I'm be very wary of making parts of the validation chain optional, for the risk of them not being enforced when they should. Strong tests would perhaps allay these fears.

As a first step I'd also want to look at whether something like this has been done in AuthLib, or if this is only something that applies to the more targeted nature of this package. My aim is to follow or align with AuthLib wherever possible.

Any help with that research etc. would be welcome through this issue.

**Comment by bpasham** [comment]
hi @felnne, I think it is optional and explicit in authlib, and is being explicitly validated in tokens.py at line 144

If we can pass options something like this into the decorator, then it would solve most of the python world's problem in this regard :)
![image](https://user-images.githubusercontent.com/16566076/113140364-f5ad8b00-91ed-11eb-970e-e9f4595dd34f.png)

what I am confused is how we can make the decorator arguments available in AzureJWTClaims class instance or to the validate method. I couldn't trace that. If you can provide me that guidance, my developers can implement this functionality and do a pull request.
Thanks

**Comment by sknopp** [comment]
Hi there,

i'm currently facing the same problem as @bpasham. In my case the focus is primarily on using an Azure AD B2C tenant.
Therefore I've implemented the different mechanism of B2C tenants to acquire the JWTS source url from the userflow openid configuration document.

For details please [have a look here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview#validate-signature).

After that I was able to successfully validate access tokens from B2C without disabling any validation mechanisms. I think thats a much more safe approach.

I'll create a pull request later when I'm sure everything works as expected.

**Comment by sknopp** [comment]
Today i was able to successfully evaluate the changes within my project and just opened the PR https://github.com/antarctica/flask-azure-oauth/pull/17 😃

**Comment by felnne** [comment]
Hi, thanks for these changes and sorry for not replying to this issue.

For info I have now rewritten this package to use a newer AuthLib version and switch to using PyJWT for validating tokens.

This new version (v0.8.0) should be _significantly_ easier to update with things like this.

If that's something that's still useful please re-open this issue and I'm happy to collaborate on a solution.

Thanks.
