### ISSUE TITLE
No return when scope operator is 'OR' none of the required scope/roles are not in 

### ISSUE THREAD

**Issue by MendezBytes** [antarctica/flask-entra-auth#15]
I believe there is a minor bug where scope_insufficent should return True when the operator is OR and none of the resource scopes are in the token_scope. Currently the ValueError is raised. Attached an image where I edited

![image](https://user-images.githubusercontent.com/13033849/118386298-898fb680-b5e4-11eb-9368-9e85a513c4af.png)

**Comment by felnne** [comment]
This library has been rewritten and is based on a newer version of AuthLib.

The new version does not override the scope resolution functionality and uses the AuthLib function directly which hopefully resolves this bug.

If not please re-open this issue.
