### ISSUE TITLE
Authlib 1.x support?

### ISSUE THREAD

**Issue by RRGTHWAR** [antarctica/flask-entra-auth#32]
Is there any chance of an update to support Authlib 1.x? They're on 1.2.0, and it looks like that would resolve some deprecation warnings and allow compatibility with Flask 2.3.

Love this library, by the way!

**Comment by RRGTHWAR** [comment]
Dang. Sorry to hear that, but I understand. Thanks for the quick response!

**Comment by RRGTHWAR** [comment]
Man, Authlib is remarkably obtuse. I see what you mean by "quite a few problems." I spent some time trying to update this library to be compatible with Authlib 1.2.0, and I made a lot of progress, but I could not for the life of me figure out how to get it to consider the incoming signatures valid.

If anyone else lands here, the (imperfect) solution I landed on was doing some minor surgery on Authlib 0.14.3 to replace _app_ctx_stack uses with g references in the Flask resource protectors. I got everything working and got rid of the deprecation warnings. That proved much easier than updating flask-azure-oauth to work with a library that only vaguely resembles its own earlier version. Not a permanent solution, but it works for now.

**Comment by felnne** [comment]
@RRGTHWAR for info - if this is still something that would be useful I've now updated this library (or rather re-written it).

This includes upgrading to the latest AuthLib version and rewriting the resource protector and token validator. Functionality wise it stays (mostly) the same and use-wise it's very similar in terms of offering a decorator.

The project README has an updated usage example that should explain that better.

Feel free to re-open this if there's still a problem.
